### ISSUE TITLE
Script should check for free disk space before running fio tests

### ISSUE THREAD

**Issue by webdock-io** [masonr/yet-another-bench-script#12]
If system does not have about 2GB available then write tests will yield 0 and read tests may (?) be inaccurate

**Comment by masonr** [comment]
Addressed in b069a5e

**Comment by compuguy** [comment]
I think this may need to be reopened because it seems to mistake swap space with disk space on EC2 instances. For example on a EC2 m5.xlarge instance:

`# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
#              Yet-Another-Bench-Script              #
#                     v2020-12-29                    #
# https://github.com/masonr/yet-another-bench-script #
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #

Fri May 14 14:46:06 UTC 2021

Basic System Information:
---------------------------------
Processor  : Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
CPU cores  : 4 @ 2500.018 MHz
AES-NI     : ✔ Enabled
VM-x/AMD-V : ❌ Disabled
RAM        : 15.1 GiB
Swap       : 2.0 GiB
Disk       : 17.3 GiB

Less than 2GB of space available. Skipping disk test...`

The instance has enough disk space to run the fio tests.

**Comment by masonr** [comment]
@compuguy - Hey there! It'll check for free space in the same directory that you run the script. Is it possible that the directory that you were in didn't have 2GB of free space available on that partition?

It'll check for free space using the command: `df -k . | awk 'NR==2{print $4}'`

The output of that will be in kilobytes and must be larger than 2097152 (2GB) for the test to proceed.

**Comment by compuguy** [comment]
@masonr I'm pretty sure the home directory on that EC2 instance had more than 2 GiB of disk space. The basic system information from the scripts output confirms it had 17.3 GiB. When I get a chance I'll spin up another EC2 instance with the latest CentOS SPEL AMI: https://github.com/plus3it/spel

**Comment by masonr** [comment]
@compuguy - The home directory has ~1GB of space:

/dev/mapper/VolGroup00-homeVol     999320    2604    **927904**   1% /home

Seems the only partition that could handle running the test is in /var/log/audit.
