### ISSUE TITLE
Automatic benchmark with graphical output data

### ISSUE THREAD

**Issue by alfredonodo** [masonr/yet-another-bench-script#19]
Hi,
I found your script very useful. Are you planning to add the possibility to automate benchmark and to display graphical output data?
Thank you

**Comment by masonr** [comment]
Glad you find the script helpful for your usage!

Automating it should be pretty easy with cron. Something like below in your crontab would do the trick to run it automatically once a week and save the output to a log file --

```
0 0 * * 0 cd /home/user/yabs && DATE=`date "+%F-%T"` curl -sL yabs.sh | bash >> yabs_"$DATE".log
```
Adjust as needed.

I'm not sure what you mean by "graphical output data". Could you elaborate on that more and/or give me an example of what you'd like to see?

**Comment by alfredonodo** [comment]
Hi,
thank you for your fast reply. It would be good to have graphical output data with statistics extracted from logs. If it is out of scope of the tool, aggregated statistics of output would be good.

**Comment by masonr** [comment]
I think any kind of graphic output would be out of scope, because a primary aim of the script is not to have any dependencies to be installed on the host machine in order for it to run. Adding in something that would generate graphics would make it too heavyweight and require additional dependencies, I would think. Might be an interesting fork if you decide to pursue something like that.

Also, I'm not sure what could really be aggregated more than it already is. Each of the tests (disk, network, geekbench) are pretty independent from each other. Outlined in issue #9, we're exploring the possibility of uploading the YABS results to a central web repo that would have results that can be searched/browsed. Perhaps that would be the thing that you're looking for, but it is some time off as we're just discussing initial development approaches now.

**Comment by alfredonodo** [comment]
Ok thank you for the reply. The issue #9 it is something at I'm looking for.
