### ISSUE TITLE
Add support for ARM

### ISSUE THREAD

**Issue by BKPepe** [masonr/yet-another-bench-script#21]
Hi,

I noticed that currently, there are supported two architectures: `x86_64` and `i?86`.  There might be ARM servers and SBC, which are using ARM architecture. 

Would it be possible to add support for it? I noticed that Geekbench is not present for ARM too much. I could find only this:

- http://support.primatelabs.com/discussions/geekbench/70-geekbench-for-linux-arm where is a version 2.4.2, which works for me.

And then this: http://support.primatelabs.com/discussions/geekbench/30140-geekbench-4-on-linux-for-arm (no provided version publicly AFAIK)

**Comment by masonr** [comment]
I'm open to adding ARM support, however I'm wary about adding such an old version of Geekbench (v2) and using a non-authoritative source. I'd be more comfortable adding in fio and iperf tests (which both seem doable with ARM) and waiting on adding in GB until there's official support for it. I read a comment on the primatelabs forum that indicated ARM compatibility was being worked on and had an ETA of end of 2020 -- can't find that comment anymore, but hopefully that means an official release will be made available soon.

**Comment by cyagon** [comment]
There is a preview version available: https://cdn.geekbench.com/Geekbench-5.4.0-LinuxARMPreview.tar.gz (from http://support.primatelabs.com/discussions/geekbench/35330-geekbench-5-for-raspberry-pi).

There are executables for both aarch64 and armv7
![image](https://user-images.githubusercontent.com/32183089/113482481-3849be80-949f-11eb-9617-e559f78367e9.png)

But this warning is showing up when geekbench is executed:
![image](https://user-images.githubusercontent.com/32183089/113482635-cfaf1180-949f-11eb-97ca-c15422a1f27e.png)

But otherwise, it ran fine on my Odroid: https://browser.geekbench.com/v5/cpu/7256766

**Comment by masonr** [comment]
I've made good progress the past couple days with the ARM-compatible YABS build. I was able to successfully cross compile static builds of fio and iperf3 (with the help of musl [http://musl.cc/] inside of the Holy Build Box container). I've made some slight changes to the script and have tested the binaries and Geekbench on a Raspberry Pi 3B that I had lying around with an aarch64 OS loaded.

One change I did need to make was to alter the fio test file from 2G down to 512M since it was struggling to run using the SD card. Will be building and testing with aarch32/armv7 soon as well. Once fully tested and verified, I'll commit the changes to the repo and we should be good to go.

After the changes are added, ARM compatibility will be consider "experimental" as I don't have access to any ARM devices besides a few Pi's. I'll need the community's help to test further and verify full functionality.

**Comment by masonr** [comment]
ARM support has been added in 857e14e

This will be considered "experimental" for awhile until sufficient testing on distinct ARM devices has been done. If you are able to, please test with any ARM devices you have. I have only been able to test with a Raspberry Pi 3B that I have so far. Thanks!

Closing this issue for now, will reopen if there's any major issues identified.
