### ISSUE TITLE
Pre-compiled fio uses instructions that are absent in QEMU emulated CPU

### ISSUE THREAD

**Issue by trimsj** [masonr/yet-another-bench-script#3]
The provided pre-compiled `fio` uses AVX instructions, and produces an Illegal instruction error on the QEMU's default emulated CPU. Please consider providing a binary compiled with `-march=x86-64 -mtune=generic`.

**Comment by trimsj** [comment]
> compiled with `-march=x86-64 -mtune=generic`.

Oops, it should be `--disable-native` in `./configure`, see 
https://github.com/axboe/fio/blob/master/configure#L251

**Comment by masonr** [comment]
Thanks! I'll get this incorporated and start testing it out :)

**Comment by masonr** [comment]
Fixed in 9819339

**Comment by Daniel15** [comment]
Does this affect perf? I wonder if this change will show lower performance on some systems.

**Comment by masonr** [comment]
@Daniel15 - iperf was not affected by this as it doesn't incorporate AVX-specific CPU instructions in the binary. The fio binary was facing much more incompatibility issues compared to the iperf binary (which has rarely caused problems). 

In any case, if a local binary/package is installed and found, the script will automatically defer to that instead of grabbing the pre-compiled binaries. So if worried about possible performance hits, feel free to install fio/iperf3 natively before running the script.

**Comment by trimsj** [comment]
> I wonder if this change will show lower performance on some systems.

@Daniel15 I doubt it will, since it is mainly a I/O benchmark tool, not a CPU one.

The `fio` packages provided by Linux distributions are all compiled with `--disable-native` (e.g., [Ubuntu](http://archive.ubuntu.com/ubuntu/pool/universe/f/fio/fio_3.12-2.debian.tar.xz)) otherwise it won't run on a lot of machines.
