### ISSUE TITLE
process '[redacted]/Geekbench-5.4.5-Linux/geekbench_x86_64' started with executable stack

### ISSUE THREAD

**Issue by jim-perkins** [masonr/yet-another-bench-script#42]
process '[redacted]/Geekbench-5.4.5-Linux/geekbench_x86_64' started with executable stack #42 

I notice this in my dmesg log when I run yabs on ubuntu 22.04 .  When I chased down geekbench it doesnt seem to be an open source program.  I did find this https://github.com/cloudharmony/geekbench5 , but I dont believe that is the source code.  Geekbench appears to be a commercial product.

So is this safe to run ?? I dont know
https://lore.kernel.org/lkml/20191208171918.GC19716@avx2/
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/fs/exec.c?id=47a2ebb7f5053387f5753b524f4920b9b829f922
It really is over my head.

Although its cool , not really a fan of running a script straight from wget/curl.  yea I know I dont have to.  Then the script downloads a compiled file that generates this cryptic warning.  Yes I can disable the geekbench test with -g .

So  is geekbench free ?  I see some mentions of a license file in the yabs.sh ?  Makes me wonder that there could possibly be an open source benchmark utility that could be ran instead ??

I discovered yabs when my VM provider asked me to run it .  It has been helpful.  thanks for the work and your time answering my questions

**Comment by masonr** [comment]
Sorry for the delay addressing this... slipped under my radar.

You are correct that geekbench is a proprietary, closed-source product. The YABS project has several disclaimers that everything included here is "run at your own risk". I've done my best to make everything as transparent as possible by open sourcing the script, showing the compilation steps for the fio/iperf binaries, allowing the user to both to defer to locally installed version or to skip certain tests entirely, not requiring root/privileged access for any of the tests, etc. -- all in an effort to put all the cards on the table while keeping security in mind. Ultimately, it's up to the end user if they feel comfortable enough to run this code.

There are a few open source system benchmark projects in the wild, sysbench comes to mind in particular. I used geekbench because it's widely used and accepted in the hosting communities to evaluate CPU performance and provides a quick and easy way to compare scores and results across different system configurations and CPUs. I may take a stab at adding an option for a tool such as sysbench to be used in place of geekbench, but for now it'll remain as is.

Anyways I appreciate you reaching out and raising your concerns. Feel free to ask any additional questions you had and I'll do my best to answer them. Thanks for using YABS! Cheers!

-Mason

**Comment by jim-perkins** [comment]
So is this safe to run ?? I dont know
https://lore.kernel.org/lkml/20191208171918.GC19716@avx2/
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/fs/exec.c?id=47a2ebb7f5053387f5753b524f4920b9b829f922
It really is over my head.
