### ISSUE TITLE
Write permission error

### ISSUE THREAD

**Issue by 0xNeu** [masonr/yet-another-bench-script#53]
I have a fresh install of Debian bullseye and I can't run YABS, getting the following error:

```
bash: line 260: /dev/null: restricted: cannot redirect output
You do not have write permission in this directory. Switch to an owned directory and re-run the script.
```

I am root and I have tried adding sudo as well `curl -sL yabs.sh | sudo bash`.

**Comment by masonr** [comment]
As far as I can tell, it's because you're in a "restricted shell" ([man page](https://www.gnu.org/software/bash/manual/html_node/The-Restricted-Shell.html)). This is new territory for, so I'm not sure how to overcome this, but you'll essentially need to be able to launch a shell that is not restricted in this manner. Is this machine a VM and if so, what virtualization type?

```
~$ bash -c 'echo "hi" > /dev/null'
~$ rbash -c 'echo "hi" > /dev/null'
rbash: /dev/null: restricted: cannot redirect output
~$ sudo bash -c 'echo "hi" > /dev/null'
~$ sudo rbash -c 'echo "hi" > /dev/null'
rbash: /dev/null: restricted: cannot redirect output

```

**Comment by 0xLem0nade** [comment]
>Is this machine a VM and if so, what virtualization type?

It's a VPS running in KVM.

YABS output:
```
Basic System Information:
---------------------------------
Uptime     : 0 days, 23 hours, 37 minutes
Processor  : Intel Core Processor (Broadwell, IBRS)
CPU cores  : 1 @ 2599.996 MHz
AES-NI     : ✔ Enabled
VM-x/AMD-V : ✔ Enabled
RAM        : 935.1 MiB
Swap       : 467.5 MiB
bash: line 238: /dev/null: restricted: cannot redirect output
Disk       : 
Distro     : Ubuntu 22.04.1 LTS
Kernel     : 5.15.0-56-generic
bash: line 260: /dev/null: restricted: cannot redirect output
```

I'll contact their support see if they can help.
Thank you.
