### ISSUE TITLE
Missing zfs

### ISSUE THREAD

**Issue by claytondukes** [masonr/yet-another-bench-script#69]
Instead of:

```
TOTAL_DISK_RAW=$(df -t simfs -t ext2 -t ext3 -t ext4 -t btrfs -t xfs -t vfat -t ntfs -t swap --total 2>/dev/null | grep total | awk '{ print $2 }')
```
You should have:

```
TOTAL_DISK_RAW=$(df -t zfs -t simfs -t ext2 -t ext3 -t ext4 -t btrfs -t xfs -t vfat -t ntfs -t swap --total 2>/dev/null | grep total | awk '{ print $2 }')
```

Also, I realize YABS tests the disk from the directory it was run in (right?), but it would be super handy to at least print out the disk mount it is testing to make sure.

**Comment by masonr** [comment]
Hi there -- the absence of ZFS from the disk space calculation is a known issue/limitation due to the way the script calculates disk space. More info in a previous issue: #35. 

I've left zfs out of the detected disk types as `df` does not accurately tally the zfs volumes as expected and often double-counts the space. Until a workaround is identified, I probably should put in some sort of warning in the readme or script output that notes the issue.

> Also, I realize YABS tests the disk from the directory it was run in (right?), but it would be super handy to at least print out the disk mount it is testing to make sure.

That's correct. Thanks for the suggestion, I agree knowing which disk/volume is being tested would definitely be of value. I'll consider adding this into a future script update!
