### ISSUE TITLE
Three Enhancements request

### ISSUE THREAD

**Issue by bilalinamdar** [masonr/yet-another-bench-script#72]
Hi,
This is nice little tool helps a lot.

**3 enhancement request**

1) What the current OS / Disk / partition block size is been used or running where the fio test is conducted. Show that.
2) Display Latency of Disk with FIO data. Without Latency data it is very hard to determine the Database related usage.
3) In your github page readme please include how to use it on Windows as most people will be able to utilize it than on windows too. I know it needs WSL v2 but it is not mentioned in your readme.

Everything else seems to be covered. :)

Regards,
Bilal Inamdar

**Comment by masonr** [comment]
Hi there!

Excellent suggestions! Really appreciate the constructive input here.

To address each:
1. Yes! This is something that has been requested a few times, so it's on my short list of improvements to add -- showing which partition the fio test is being ran in as well as adding some documentation better describing how to test multiple partitions, etc.
2. Good point! I'll try to see how easy it would be to grep the latency information and display that in the tables somewhere.
3. Thanks for pointing that out. I could've sworn I had put something in the Readme about Windows support via WSL v2, but that may have just been on external forums instead. I'm starting to work on a documentation section now so that this information is more organized and the Readme can be further simplified.

More to follow as each of these issues gets addressed. Thanks again!
